import type { CollectionConfig } from "payload";
import { isStaffOrAgent } from "../access";

/**
 * One row per calendar day (Asia/Makassar) representing the 16-article
 * homepage selection for that day.
 *
 * Generated by `scripts/pick-daily-feed.mjs` (cron at 04:00 GMT+8).
 * The picker is idempotent — if a row already exists for the date,
 * it's a no-op.
 *
 * Selection rules:
 *   • 16 articles total = 2 per topic × 8 topics
 *   • each topic's 2 articles come from 2 different areas (when possible)
 *   • sort key: (homeFeaturedCount ASC, homeLastFeaturedAt NULLS FIRST ASC, random())
 *   • after picking, the picker bumps homeFeaturedCount + sets
 *     homeLastFeaturedAt = today on the 16 selected articles
 *
 * Cycle math at full population (1280 published):
 *   1280 / 16 = 80 days before any article repeats
 */
export const HomeDailyFeed: CollectionConfig = {
  slug: "home-daily-feed",
  labels: { singular: "Home Daily Feed", plural: "Home Daily Feed" },
  admin: {
    useAsTitle: "date",
    group: "System",
    description:
      "Snapshot of the 16-article homepage selection per day. Auto-generated by the picker cron at 04:00 GMT+8 (20:00 UTC). Read-only in practice — the cron owns the writes.",
    defaultColumns: ["date", "generatedAt", "seed"],
    listSearchableFields: ["date"],
    pagination: { defaultLimit: 30 },
  },
  defaultSort: "-date",
  access: {
    read: () => true,
    create: isStaffOrAgent,
    update: isStaffOrAgent,
    delete: isStaffOrAgent,
  },
  fields: [
    {
      name: "date",
      type: "date",
      required: true,
      unique: true,
      index: true,
      admin: {
        description: "Calendar date in Asia/Makassar (UTC+8).",
        date: { pickerAppearance: "dayOnly" },
      },
    },
    {
      name: "slots",
      type: "array",
      required: true,
      minRows: 0,
      maxRows: 16,
      admin: {
        description:
          "16 picked articles in render order. Each slot is one of the 4×4 grid tiles.",
      },
      fields: [
        {
          type: "row",
          fields: [
            {
              name: "slotIndex",
              type: "number",
              required: true,
              admin: { description: "0–15, render order in the 4×4 grid." },
            },
            { name: "topic", type: "relationship", relationTo: "topics", required: true },
          ],
        },
        { name: "article", type: "relationship", relationTo: "articles", required: true },
      ],
    },
    {
      name: "seed",
      type: "number",
      admin: {
        description:
          "Date-derived seed used by the picker. Survives a re-run for diagnostics.",
      },
    },
    {
      name: "generatedAt",
      type: "date",
      admin: {
        description: "When the picker actually wrote this row.",
        date: { pickerAppearance: "dayAndTime" },
        readOnly: true,
      },
    },
  ],
};
